site_name: scRNA-Seq Datasets
pages:
    - About: index.md
    - Human:
      - Pancreas: human/pancreas.md
      - Tissues: human/tissues.md
    - Mouse:
      - Brain: mouse/brain.md
      - Embryo Devel: mouse/edev.md
      - Embryo Stem Cells: mouse/esc.md
      - Pancreas: mouse/pancreas.md
      - Retina: mouse/retina.md
      - Tissues: mouse/tissues.md
theme: 'material'
docs_dir: 'website'
site_dir: 'docs'
google_analytics:
  - 'UA-91539252-1'
  - 'auto'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/hemberg-lab/scRNA.seq.datasets'
extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'
markdown_extensions:
  - admonition

repo_name: hemberg-lab/scRNA.seq.datasets
repo_url: https://github.com/hemberg-lab/scRNA.seq.datasets
